# Generated by Django 3.2.2 on 2021-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_title',
            field=models.CharField(max_length=40),
        ),
    ]
